Introduce MsoMdoc VpToken and add 'apv' and 'apu' JWE header claims o…
eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt pull request #234
Opened 2024-04-12 13:03 UTC by dzarras

Closes #177

2024-04-12 13:58 UTC, babisRoutis requested changes

2024-04-12 13:58 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/JarmJwt.kt
> +            apu?.let { agreementPartyUInfo(Base64URL.encode(it)) }
I don't think that we should encode `apu`. I think it should be provided with `VpToken.MsoMdoc` already encoded. Can you please confirm with @marinaioannou ?

2024-04-12 14:01 UTC, dzarras commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/JarmJwt.kt
> +            apu?.let { agreementPartyUInfo(Base64URL.encode(it)) }
If that's the case, should we explicitly require a Base64Url in MsoMdoc instead to avoid possible confusion?

2024-04-12 14:46 UTC, babisRoutis requested changes

2024-04-12 15:15 UTC, marinaioannou commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/JarmJwt.kt
> +            apu?.let { agreementPartyUInfo(Base64URL.encode(it)) }
@babisRoutis, @dzarras 

I agree that `apu` should be provided already encoded as base64url in `VpToken.MsoMdoc`, as following the ISO 18013-7 terminology: 
> The mdoc shall set the apu JWT (JWE) header parameter to the base64url-encoded-with-no-padding value of the mdocGeneratedNonce of the SessionTranscript as defined in clause B.4.4.

I think this would be clearer for the developers who will utilize the library.

Otherwise, we should call it `mdocGeneratedNonce` in `VpToken.MsoMdoc`.

2024-04-15 06:38 UTC, babisRoutis approved these changes

2024-04-15 06:38 UTC, merged