Draft22 - DCQL
eu-digital-identity-wallet/eudi-lib-jvm-siop-openid4vp-kt pull request #292
Opened 2024-12-05 21:50 UTC by babisRoutis

This PR adds support for DCQL

2025-01-14 08:18 UTC, dzarras commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/dcql/DCQL.kt
> +            path: ClaimPath? = null,
@babisRoutis According to the spec, `path` is required when using a JSON-based claims structure like SD-JWT VC.

Reference: https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#section-6.3

2025-01-14 08:20 UTC, dzarras commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/dcql/DCQL.kt
> +data class ClaimsQuery(
@babisRoutis Would it make sense to have an init block that requires either the presence of `path` or `namespace` + `claimName` ?

2025-01-14 08:20 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/dcql/DCQL.kt
> +            path: ClaimPath? = null,
Good catch

2025-01-14 08:49 UTC, dzarras commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/OpenId4VPSpec.kt
> +    public const val FORMAT_W3C_JSONLD_SIGNED_JWT: String = "jwt_vc_json-ld"
@babisRoutis `jwt_vc_json-ld` is not mentioned in OpenId4VP, but rather in OpenId4VCI. Would it make sense to move the format constants in the companion object of `Format`?

Reference: https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-w3c-verifiable-credentials

2025-01-14 08:49 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/dcql/DCQL.kt
> +data class ClaimsQuery(
There is [PR](https://github.com/openid/OpenID4VP/pull/368) to remove `namespace` & `claimName` and use `path` also in the `mdoc` case.

Perhaps though in the context of d23 we can add such a constraint

2025-01-14 09:03 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/OpenId4VPSpec.kt
> +    public const val FORMAT_W3C_JSONLD_SIGNED_JWT: String = "jwt_vc_json-ld"
Better remove the const values that are not used (`FORMAT_W3C_JSONLD_DATA_INTEGRITY` , `FORMAT_W3C_JSONLD_SIGNED_JWT`) and also remove the related Format instances from the companion object

2025-01-14 09:36 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/Format.kt
> +        public val SdJwtVcDeprecated: Format get() = Format(OpenId4VPSpec.FORMAT_SD_JWT_VC_DEPRECATED)
@dzarras Actually we can remove it

2025-01-15 10:47 UTC, dzarras commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/DefaultResponseDispatcher.kt
> +            is AuthorizationResponsePayload.OpenId4VPAuthorization -> {
@gdimtsas Could you please extract this to an extension function to avoid code duplication?

i.e.:

```kotlin
internal fun MutableMap<String,String>.put(vpContent: VpContent): Unit
```

2025-01-15 11:05 UTC, dzarras commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/JarmJwt.kt
> +    val (apv, apu) = when (data.encryptionParameters) {
@gdimtsas You can introduce a local variable in the when expression and have the compiler smart-cast.
i.e.
```kotlin
    val (apv, apu) = when (val encryptionParameters = data.encryptionParameters) {
        is EncryptionParameters.DiffieHellman -> encryptionParameters.apu
        else -> null
    }?.let { Base64URL.encode(data.nonce) to it } ?: (null to null)
```

2025-01-15 11:09 UTC, dzarras commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/JarmJwt.kt
> +                        put(ID_TOKEN_CLAIM, data.idToken)
@gdimtsas This is not correct. `id_token` must **always** be populated in this case.

2025-01-15 11:13 UTC, dzarras commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/JarmJwt.kt
> +                when (data.vpContent) {
@gdimtsas Could you please introduce an extension function over `JsonObjectBuilder` to avoid code duplication?
i.e.
```kotlin
        fun JsonObjectBuilder.put(vpContent: VpContent) {
            when (vpContent) {
                is VpContent.PresentationExchange -> {
                    put(VP_TOKEN_CLAIM, vpContent.verifiablePresentations.toJson())
                    put(PRESENTATION_SUBMISSION_CLAIM, Json.encodeToJsonElement(vpContent.presentationSubmission))
                }
                is VpContent.DCQL -> put(VP_TOKEN_CLAIM, vpContent.verifiablePresentations.toJson())
            }
        }
```
Define it locally in `JsonObjectBuilder.payloadClaims` and not as a top-level function.

2025-01-15 11:55 UTC, gdimtsas commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/internal/response/JarmJwt.kt
> +                        put(ID_TOKEN_CLAIM, data.idToken)
You're right, I missed this one.

2025-01-15 13:16 UTC, dzarras requested changes

2025-01-20 11:25 UTC, dzarras commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/dcql/DCQL.kt
> +    @SerialName(OpenId4VPSpec.DCQL_META) val meta: JsonObject? = null,
@vafeini My interpretation of the spec, is that yes it is open ended and defined by the specific format. OpenId4VP currently provided the structure of the metadata object for SD-JWT VC and Mso Mdoc.

https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#section-6.1-3.6

2025-01-20 11:28 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/dcql/DCQL.kt
> +    @SerialName(OpenId4VPSpec.DCQL_META) val meta: JsonObject? = null,
No we shouldn't limit it.

Currently there are some rules, per format, and I think that there also some format specific access methods. 
I guess that this is enough for now.

The `@see` in the comments above meta is not complete though because it points just to the mso_mdoc meta. There should be a reference to the accessor for the sd-jwt-vc

2025-01-20 11:43 UTC, dzarras commented on src/main/kotlin/eu/europa/ec/eudi/openid4vp/dcql/DCQL.kt
> +    @SerialName(OpenId4VPSpec.DCQL_META) val meta: JsonObject? = null,
@babisRoutis Just added the missing references.

2025-01-21 13:34 UTC, dzarras commented on src/test/kotlin/eu/europa/ec/eudi/openid4vp/Example.kt
> +    data class OpenId4VPPrEx(val presentationDefinition: String) : Transaction
@gdimtsas Even though this is a showcase example, I prefer if we kept the `Transaction` hierarchy intact. What we need is update the payload of the `OpenId4VP` case.

For instance:
```kotlin
sealed interface VpQuery {
  data class PresentationExachange(val presentationDefinition: String): VpQuery
  data class DCQL(val query: String): VpQuery
}

data class OpenId4VP(val query: VpQuery) : Transaction

suspend fun <T> Transaction.fold(
    ifSiop: suspend () -> T,
    ifOpenId4VP: suspend (VpQuery) -> T,
): T

        private suspend fun initOpenId4VpTransaction(
            client: HttpClient,
            verifierApi: URL,
            nonce: String,
            query: VpQuery,
        ): JsonObject {
            verifierPrintln("Placing to verifier endpoint OpenId4Vp authorization request  ...")
            val request =
                """
                    {
                        "type": "vp_token",
                        "nonce": "$nonce",
                        ...,
                        "response_mode": "direct_post.jwt" ,
                        "presentation_definition_mode": "by_reference"
                        "jar_mode": "by_reference",
                        "wallet_response_redirect_uri_template":"https://foo?response_code={RESPONSE_CODE}"       
                    }
                """.trimIndent()
            return initTransaction(client, verifierApi, request)
        }
```

2025-01-21 14:59 UTC, merged